version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: my-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

  backend:
    build: ./backend/server
    container_name: my-server
    restart: always
    env_file:
      - ./backend/server/.env
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:

